---
- name: Configure OSPF routing protocol
  hosts: routers
  gather_facts: no
  connection: network_cli
  vars_files:
    - secrets.yml
  tasks:
    - name: Enable OSPF
      ios_config:
        lines:
          - router ospf 1
      ignore_errors: yes


    - name: Jinja2 Template
      template:
        src: ospf.j2
        dest: ospfconfig.txt

    - name: Configure OSPF Networks
      ios_config:
        lines:
          - "{{ lookup('file', 'ospfconfig.txt') }}"
      ignore_errors: yes

