---
- name: Basic Network Setup
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure unique hostname
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}

    - name: Configure strong local passwords
      ios_config:
        lines:
          - enable secret cisco
          - username ansible privilege 15 secret cisco

    - name: Disable Telnet and enable SSH
      ios_config:
        lines:
          - no ip telnet server
          - ip ssh version 2
          - line vty 0 4
          - transport input ssh
          - login local
      ignore_errors: yes

    - name: Configure logging and timestamps
      ios_config:
        lines:
          - logging buffered 8192
          - service timestamps debug datetime msec
          - service timestamps log datetime msec
      ignore_errors: yes

    - name: Configure VLANs for network segmentation
      ios_config:
        lines:
          - int g1/0.1
          - encapsulation dot1Q 10
          - no shut
          - exit
          - int g1/0.2
          - encapsulation dot1Q 20
          - no shut
          - exit
          - int g1/0.3
          - encapsulation dot1Q 30
          - no shut
          - exit
      ignore_errors: yes
